using LabelVerify.Web.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LabelVerify.Web.Services
{
    public class PdfAuditReportGenerator
    {
        public byte[] Generate(ComplianceAuditReport report)
        {
            return Document.Create(container =>
            {
                BuildCoverPage(container, report);
                BuildAuditReportPage(container, report);
            }).GeneratePdf();
        }

        private static void BuildCoverPage(IDocumentContainer container, ComplianceAuditReport report)
        {
            container.Page(page =>
            {
                page.Margin(30);

                page.Content().Column(col =>
                {
                    col.Spacing(12);

                    col.Item()
                        .AlignCenter()
                        .Text("TTB Label Review Package")
                        .FontSize(24)
                        .Bold();

                    col.Item()
                        .AlignCenter()
                        .Text($"Review ID: {report.ReviewId}")
                        .FontSize(12);

                    col.Item().PaddingVertical(10);

                    col.Item().Text("Executive Summary")
                        .FontSize(16)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Brand Name", report.BrandName ?? report.ApprovedProfile.BrandName);
                        AddRow(table, "Recommendation", report.Recommendation);
                        AddRow(table, "Risk Level", report.RiskLevel ?? "N/A");
                        AddRow(table, "Risk Score", report.RiskScore.ToString());
                        AddRow(table, "Reviewer", report.ReviewerName ?? "Unassigned");
                        AddRow(table, "Review Date", report.ReviewDateUtc.ToString("g"));
                    });

                    var riskColor =
                        report.RiskLevel == "High"
                            ? Colors.Red.Lighten2
                            : report.RiskLevel == "Medium"
                                ? Colors.Orange.Lighten2
                                : Colors.Green.Lighten2;

                    col.Item()
                        .Background(riskColor)
                        .Padding(12)
                        .Text($"Risk Level: {report.RiskLevel ?? "N/A"} ({report.RiskScore})")
                        .FontSize(18)
                        .Bold();

                    col.Item().Text("AI Executive Summary")
                        .FontSize(16)
                        .Bold();

                    col.Item()
                        .Background(Colors.Blue.Lighten5)
                        .Padding(12)
                        .Text(string.IsNullOrWhiteSpace(report.AiComplianceSummary)
                            ? "No AI summary available."
                            : report.AiComplianceSummary)
                        .FontSize(10);

                    col.Item().Text("Disposition Snapshot")
                        .FontSize(16)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Final Disposition", report.FinalDisposition ?? "Pending");
                        AddRow(table, "Disposition Date", report.DispositionDateUtc?.ToString("g") ?? "Pending");
                        AddRow(table, "Workflow Status", report.WorkflowStatus ?? "Open");
                    });
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by LabelVerify AI");
            });
        }

        private static void BuildAuditReportPage(IDocumentContainer container, ComplianceAuditReport report)
        {
            container.Page(page =>
            {
                page.Margin(30);

                page.Header()
                    .Text("LabelVerify Compliance Audit Report")
                    .FontSize(20)
                    .Bold();

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Text($"Review Date: {report.ReviewDate:u}");
                    col.Item().Text($"Recommendation: {report.Recommendation}").Bold();
                    col.Item().Text($"Overall Score: {report.OverallScore}%");

                    col.Item().LineHorizontal(1);

                    if (!string.IsNullOrWhiteSpace(report.AiComplianceSummary))
                    {
                        col.Item().Text("AI Compliance Summary")
                            .FontSize(14)
                            .Bold();

                        col.Item()
                            .Background(Colors.Blue.Lighten5)
                            .Padding(10)
                            .Text(report.AiComplianceSummary)
                            .FontSize(10);

                        col.Item().LineHorizontal(1);
                    }

                    col.Item().Text("Risk Assessment")
                        .FontSize(14)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Risk Score", report.RiskScore.ToString());
                        AddRow(table, "Risk Level", report.RiskLevel ?? "N/A");
                        AddRow(table, "Risk Factors", report.RiskFactors ?? "N/A");
                    });

                    if (!string.IsNullOrWhiteSpace(report.AiRiskAssessment))
                    {
                        col.Item()
                            .Background(Colors.Orange.Lighten5)
                            .Padding(10)
                            .Text(report.AiRiskAssessment)
                            .FontSize(10);
                    }

                    col.Item().Text("Reviewer Decision")
                        .FontSize(14)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Reviewer", report.ReviewerName ?? "N/A");
                        AddRow(table, "Final Disposition", report.FinalDisposition ?? "N/A");
                        AddRow(table, "Disposition Date", report.DispositionDateUtc?.ToString("u") ?? "N/A");
                        AddRow(table, "Reviewer Notes", report.ReviewerNotes ?? "N/A");
                    });

                    col.Item().Text("Approved Product Profile")
                        .FontSize(14)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddRow(table, "Brand Name", report.ApprovedProfile.BrandName);
                        AddRow(table, "Fanciful Name", report.ApprovedProfile.FancifulName);
                        AddRow(table, "Class / Type", report.ApprovedProfile.ClassType);
                        AddRow(table, "Alcohol Content", report.ApprovedProfile.AlcoholContent);
                        AddRow(table, "Net Contents", report.ApprovedProfile.NetContents);
                        AddRow(table, "Government Warning", report.ApprovedProfile.GovernmentWarning);
                    });

                    col.Item().Text("Verification Results")
                        .FontSize(14)
                        .Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(1.5f);
                            columns.RelativeColumn(1.5f);
                            columns.RelativeColumn(1.5f);
                            columns.RelativeColumn(1.5f);
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        Header(table, "Field");
                        Header(table, "Approved");
                        Header(table, "Production");
                        Header(table, "Found On");
                        Header(table, "Status");
                        Header(table, "Confidence");

                        foreach (var check in report.VerificationResult.Checks)
                        {
                            Cell(table, check.FieldName);
                            Cell(table, check.ExpectedValue);
                            Cell(table, check.ActualValue);
                            Cell(table, check.SourceLabel);
                            Cell(table, check.Status);
                            Cell(table, check.WasSkipped ? "N/A" : $"{check.ConfidenceScore}%");

                            if (!string.IsNullOrWhiteSpace(check.AiAnalysis))
                            {
                                table.Cell()
                                    .ColumnSpan(6)
                                    .Background(Colors.Grey.Lighten4)
                                    .Padding(6)
                                    .Text($"AI Analysis: {check.AiAnalysis}")
                                    .FontSize(9);
                            }
                        }
                    });
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by LabelVerify AI");
            });
        }

        private static void AddRow(TableDescriptor table, string label, string? value)
        {
            Cell(table, label);
            Cell(table, string.IsNullOrWhiteSpace(value) ? "Not detected" : value);
        }

        private static void Header(TableDescriptor table, string text)
        {
            table.Cell()
                .Background(Colors.Grey.Lighten2)
                .Padding(5)
                .Text(text)
                .Bold();
        }

        private static void Cell(TableDescriptor table, string? text)
        {
            table.Cell()
                .BorderBottom(1)
                .BorderColor(Colors.Grey.Lighten2)
                .Padding(5)
                .Text(string.IsNullOrWhiteSpace(text) ? "Not detected" : text);
        }
    }
}