using LabelVerify.Web.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LabelVerify.Web.Services
{
    public class PdfAuditReportGenerator
    {
        public byte[] Generate(ComplianceAuditReport report)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header().Text("LabelVerify Compliance Audit Report")
                        .FontSize(20)
                        .Bold();

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Review Date: {report.ReviewDate:u}");
                        col.Item().Text($"Recommendation: {report.Recommendation}").Bold();
                        col.Item().Text($"Overall Score: {report.OverallScore}%");

                        col.Item().LineHorizontal(1);

                        if (!string.IsNullOrWhiteSpace(report.AiComplianceSummary))
                        {
                            col.Item().Text("AI Compliance Summary")
                                .FontSize(14)
                                .Bold();

                            col.Item()
                                .Background(Colors.Blue.Lighten5)
                                .Padding(10)
                                .Text(report.AiComplianceSummary)
                                .FontSize(10);

                            col.Item().LineHorizontal(1);
                        }

                        col.Item().Text("Approved Product Profile").FontSize(14).Bold();

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });

                            AddRow(table, "Brand Name", report.ApprovedProfile.BrandName);
                            AddRow(table, "Fanciful Name", report.ApprovedProfile.FancifulName);
                            AddRow(table, "Class / Type", report.ApprovedProfile.ClassType);
                            AddRow(table, "Alcohol Content", report.ApprovedProfile.AlcoholContent);
                            AddRow(table, "Net Contents", report.ApprovedProfile.NetContents);
                            AddRow(table, "Government Warning", report.ApprovedProfile.GovernmentWarning);
                        });

                        col.Item().Text("Verification Results").FontSize(14).Bold();

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn(1.5f);
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });

                            Header(table, "Field");
                            Header(table, "Approved");
                            Header(table, "Production");
                            Header(table, "Found On");
                            Header(table, "Status");
                            Header(table, "Confidence");

                            foreach (var check in report.VerificationResult.Checks)
                            {
                                Cell(table, check.FieldName);
                                Cell(table, check.ExpectedValue);
                                Cell(table, check.ActualValue);
                                Cell(table, check.SourceLabel);
                                Cell(table, check.Status);
                                Cell(table, check.WasSkipped ? "N/A" : $"{check.ConfidenceScore}%");
                            }
                        });
                    });

                    page.Footer().AlignCenter().Text("Generated by LabelVerify AI");
                });
            }).GeneratePdf();
        }

        private static void AddRow(TableDescriptor table, string label, string value)
        {
            Cell(table, label);
            Cell(table, string.IsNullOrWhiteSpace(value) ? "Not detected" : value);
        }

        private static void Header(TableDescriptor table, string text)
        {
            table.Cell()
                .Background(Colors.Grey.Lighten2)
                .Padding(5)
                .Text(text)
                .Bold();
        }

        private static void Cell(TableDescriptor table, string? text)
        {
            table.Cell()
                .BorderBottom(1)
                .BorderColor(Colors.Grey.Lighten2)
                .Padding(5)
                .Text(string.IsNullOrWhiteSpace(text) ? "Not detected" : text);
        }
    }
}